databases:
  - name: quid_pro_quo
    databaseName: quid_pro_quo
    user: quid_pro_quo_user
    plan: free

services:
  - type: web
    name: mysite
    runtime: ruby
    plan: free
    buildCommand: >
      bundle install &&
      yarn install --check-files &&
      bundle exec rake assets:precompile &&
      bundle exec rails db:migrate &&
      bundle exec rails db:seed
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync:false- key: WEB_CONCURRENCY
        value: 2 # sensible default