# PostgreSQL
#
# Install the PostgreSQL driver
#   gem install pg
#
# Ensure the PostgreSQL gem is defined in your Gemfile
#   gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: root
  host: localhost

development:
  <<: *default
  database: quid_pro_quo_development

test:
  <<: *default
  database: quid_pro_quo_test

production:
  primary: &primary_production
    <<: *default
    database: quid_pro_quo_production
    username: quid_pro_quo
    password: <%= ENV["QUID_PRO_QUO_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: quid_pro_quo_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: quid_pro_quo_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: quid_pro_quo_production_cable
    migrations_paths: db/cable_migrate
